version: "3.9"

services:
  initilizationservice:
    image: cenkcamkiran/gcloud-projects:initilizationservice_v3.0
    networks:
      default: null
    restart: on-failure
    container_name: initilization_service
    environment:
      RABBITMQ_HOST: ${RABBITMQHOST}
      RABBITMQ_PORT: ${RABBITMQPORT}
      RABBITMQ_USERNAME: ${RABBITMQUSERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQPASSWORD}
      MINIO_HOST: ${MINIOHOST}
      MINIO_ACCESSKEY: ${MINIOACCESSKEY}
      MINIO_SECRETKEY: ${MINIOSECRETKEY}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_AUDIO_BUCKET_NAME: ${MINIO_AUDIO_BUCKET_NAME}
      MINIO_VIDEO_BUCKET_NAME: ${MINIO_VIDEO_BUCKET_NAME}
      ELK_HOST: ${ELKHOST}
      ELK_USERNAME: ${ELKUSERNAME}
      ELK_PASSWORD: ${ELKPASSWORD}

networks:
  default:
    name: kong_default
