version: "3.9"

services:
  initilizationservice:
    image: cenkcamkiran/gcloud-projects:initilizationservice_v3.0
    networks:
      default: null
    restart: on-failure
    container_name: initilization_service
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESSKEY: ${MINIO_ACCESSKEY}
      MINIO_SECRETKEY: ${MINIO_SECRETKEY}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_AUDIO_BUCKET_NAME: ${MINIO_AUDIO_BUCKET_NAME}
      MINIO_VIDEO_BUCKET_NAME: ${MINIO_VIDEO_BUCKET_NAME}
      ELK_HOST: ${ELK_HOST}
      ELK_USERNAME: ${ELK_USERNAME}
      ELK_PASSWORD: ${ELK_PASSWORD}

networks:
  default:
    name: kong_default
