version: "3.9"

services:
  converterservice:
    image: cenkcamkiran/gcloud-projects:converterservice_v3.0
    networks:
      default: null
    restart: on-failure
    container_name: converter_service
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESSKEY: ${MINIO_ACCESSKEY}
      MINIO_SECRETKEY: ${MINIO_SECRETKEY}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_AUDIO_BUCKET_NAME: ${MINIO_AUDIO_BUCKET_NAME}
      MINIO_VIDEO_BUCKET_NAME: ${MINIO_VIDEO_BUCKET_NAME}

networks:
  default:
    name: kong_default
