version: "3.9"

services:
  webservice:
    image: cenkcamkiran/gcloud-projects:webservice_v1.0
    #networks:
    #- microservices
    restart: on-failure
    container_name: converter_webservice
    environment:
      RABBITMQ_HOST: ${RABBITMQHOST}
      RABBITMQ_PORT: ${RABBITMQPORT}
      RABBITMQ_USERNAME: ${RABBITMQUSERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQPASSWORD}
      MINIO_HOST: ${MINIOHOST}
      MINIO_ACCESSKEY: ${MINIOACCESSKEY}
      MINIO_SECRETKEY: ${MINIOSECRETKEY}
      ELK_HOST: ${ELKHOST}
      ELK_USERNAME: ${ELKUSERNAME}
      ELK_PASSWORD: ${ELKPASSWORD}
      ELK_DEFAULT_INDEX: webservice_requestresponse_logs
      FILE_LENGTH_LIMIT: 30000000
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:4080
    # ports:
    #   - target: 4080
    #     host_ip: 127.0.0.1
    #     published: 4080
    #     protocol: tcp
    #     mode: host #host internal, ingress external. Is is similar to Kubernetes
    expose:
      - "4080"
    networks:
      - "converter-microservices"

networks:
  converter-microservices:
