version: "3.9"

services:
  notificationservice:
    image: cenkcamkiran/gcloud-projects:notificationservice_v3.0
    networks:
      default: null
    restart: on-failure
    container_name: notification_service
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      MINIO_AUDIO_BUCKET_NAME: ${MINIO_AUDIO_BUCKET_NAME}
      MINIO_VIDEO_BUCKET_NAME: ${MINIO_VIDEO_BUCKET_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_MAIL_FROM: ${SMTP_MAIL_FROM}
      SMTP_MAIL_PASSWORD: ${SMTP_MAIL_PASSWORD}
      SMTP_MAIL_USERNAME: ${SMTP_MAIL_USERNAME}

networks:
  default:
    name: kong_default
