version: "3.9"

services:
  webservice:
    image: cenkcamkiran/gcloud-projects:notificationservice_v1.0
    #volumes:
      #- webservice:/example
    #networks:
      #- microservices
    restart: on-failure
    container_name: notification_service
    environment:
      RABBITMQ_HOST: ${RABBITMQHOST}
      RABBITMQ_PORT: ${RABBITMQPORT}
      RABBITMQ_USERNAME: ${RABBITMQUSERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQPASSWORD}
      MINIO_HOST: ${MINIOHOST}
      MINIO_ACCESSKEY: ${MINIOACCESSKEY}
      MINIO_SECRETKEY: ${MINIOSECRETKEY}
      SMTP_HOST: ${SMTPHOST}
      SMTP_PORT: ${SMTPPORT}
      SMTP_MAIL_FROM: ${SMTPMAILFROM}
      SMTP_MAIL_PASSWORD: ${SMTPMAILPASSWORD}
      SMTP_MAIL_USERNAME: ${SMTPMAILUSERNAME}
      
#volumes:
  #webservice-volume:
  
#networks:
  #microservices: