version: "3.9"

services:
  loggerservice:
    image: cenkcamkiran/gcloud-projects:loggerservice_v3.0
    networks:
      default: null
    restart: on-failure
    container_name: logger_service
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      ELK_HOST: ${ELK_HOST}
      ELK_USERNAME: ${ELK_USERNAME}
      ELK_PASSWORD: ${ELK_PASSWORD}
      ELK_DEFAULT_INDEX: webservice_requestresponse_logs

networks:
  default:
    name: kong_default
