version: "3"

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${KONGDBUSER}
      - POSTGRES_DB=${KONGDBNAME}
      - POSTGRES_PASSWORD=${KONGPWD}
    networks:
      default: null
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"

  kong-migrations:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=${KONGPWD}
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - kong-database

  kong:
    image: kong
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=${KONGDBUSER}
      - KONG_PG_PASSWORD=${KONGPWD}
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=${KONG_ADMINHOST}:8001, ${KONG_ADMINHOST}:8444 ssl
    restart: on-failure
    expose:
      - 8001
      - 8444
    ports:
      - 8000:8000
      - 8443:8443
    networks:
      default: null
    links:
      - kong-database:kong-database
    depends_on:
      - kong-migrations

  konga:
    image: pantsel/konga
    ports:
      - 1337:1337/tcp
    networks:
      default: null
    links:
      - kong:kong
    container_name: konga
    environment:
      - ${KONGA_ENVIRONMENT}

volumes:
  db-data-kong-postgres:

networks:
  default:
    name: kong_default
